/*
 * This source file was generated by the Gradle 'init' task
 */
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;

public class MainApplication extends Application {

    @Override
    public void start(Stage primaryStage) throws IOException {
        URL fxmlLocation = getClass().getResource("/fxml/LoginView.fxml");
        Parent root = FXMLLoader.load(fxmlLocation);
        
        primaryStage.setTitle("OPTIK XYZ - APPS");
        primaryStage.setScene(new Scene(root, 950, 600)); // Ukuran disesuaikan untuk layout 2 panel
        primaryStage.setResizable(false);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}