/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    
    // SQLite JDBC Driver
    implementation("org.xerial:sqlite-jdbc:3.43.0.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

// Configure source sets to use the existing directory structure
sourceSets {
    main {
        java {
            srcDirs("src/main")
        }
    }
}

application {
    // Define the main class for the application.
    mainClass = "Database.DatabaseTest"
}

// Task untuk menjalankan DatabaseResepExample
tasks.register<JavaExec>("runResepExample") {
    group = "application"
    description = "Run DatabaseResepExample"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "main.Database.DatabaseResepExample"
}

// Task untuk menjalankan DatabaseInspector
tasks.register<JavaExec>("runInspector") {
    group = "application"
    description = "Run DatabaseInspector to check raw database content"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "main.Database.DatabaseInspector"
}

// Task untuk menjalankan DatabaseDokterJadwalExample
tasks.register<JavaExec>("runDokterJadwalExample") {
    group = "application"
    description = "Run DatabaseDokterJadwalExample to test Dokter and JadwalPemeriksaan functionality"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "main.Database.DatabaseDokterJadwalExample"
}

// Task untuk menjalankan Database Migration
tasks.register<JavaExec>("runMigration") {
    group = "application"
    description = "Run DatabaseMigration to update JadwalPemeriksaan table structure"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "main.Database.DatabaseMigration"
}

// Task untuk membersihkan duplikat dokter
tasks.register<JavaExec>("runDokterCleanup") {
    group = "application"
    description = "Run DokterCleanup to remove duplicate doctor records"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "main.Database.DokterCleanup"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
